### ISSUE TITLE
Twitter bot is tweeting same the 'new' packages, even though they are not new.

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/bioconductor.org_archive#10]
https://twitter.com/Bioconductor/status/663822962278187009
https://twitter.com/Bioconductor/status/663822961275703296
https://twitter.com/Bioconductor/status/663460573053628416
https://twitter.com/Bioconductor/status/663460571979849730
https://twitter.com/Bioconductor/status/663098188249874432
https://twitter.com/Bioconductor/status/663098187255816196

**Comment by mtmorgan** [comment]
In response to email last night, Dan said... 

> The tweets are based on the new package RSS feed. The script looks at all existing tweets to see if the package has been tweeted before. Must be a bug in that logic. All relevant scripts are in the crontab of biocadmin on staging. Sorry I can't be more help, it's hard enough just to get online here. Take a look and if you can drill down to more specific questions let me know.

**Comment by jimhester** [comment]
Tweets log file not terribly useful, but does reveal another issue with the twitter code (not correctly handling input over 140 characters. #4

```
# biocadmin@staging:~/bioc-test-web/tweets.log
Error tweeting consensusSeekeR: Status is over 140 characters.
successfully tweeted scde...
successfully tweeted R4RNA...
successfully tweeted globalSeq...
Error tweeting consensusSeekeR: Status is over 140 characters.
successfully tweeted scde...
successfully tweeted R4RNA...
```

**Comment by jimhester** [comment]
This seems to be because the regex at 
[scripts/tweet_new_packages.rb#L56](https://github.com/Bioconductor/bioconductor.org/blob/6f8532cd1014fd903cbb91e7a468d21d022e41ca/scripts/tweet_new_packages.rb#L56) assumes `http://`, but the latest tweets are actually `https://`. I will send a pull request.

``` rb
[14] pry(main)> tweets[1].text
=> "https://t.co/N4ll44kuIM scde Single Cell Differential Expression"
```
