### ISSUE TITLE
Error tweeting consensusSeekeR: Status is over 140 characters.

### ISSUE THREAD

**Issue by jimhester** [Bioconductor/bioconductor.org_archive#11]
from `biocadmin@staging:~/bioc-test-web/tweets.log`

**Comment by jimhester** [comment]
This is twitters official documentation on counting characters (https://dev.twitter.com/overview/api/counting-characters).

And url shortening (https://dev.twitter.com/overview/t.co)

**Comment by jimhester** [comment]
Note the previous and current code used hardcoded values (140 - 22) (now 140 - 23) for the length, and did not handle multibyte unicode characters.

Twitters docs recommend you query [GET help/configuration](https://dev.twitter.com/rest/reference/get/help/configuration) for the maximum tweet length and use something like the following to count the unicode character length.

``` rb
class String
  def display_length ActiveSupport::Multibyte::Chars.new(self).normalize(:c).length
  end
end
```

I decided to keep this fix simple so didn't do as suggested, but we may want to in the future...

Also the current code does not handle cases with more than one URL in them, but that should not happen for this use case.

**Comment by b-long** [comment]
:+1: Great find, Jim.  Also, I'd recommend anyone check out the Twitter information on [counting characters](https://dev.twitter.com/overview/api/counting-characters).  It's a great reference.  Reminded me of this old standard: http://www.joelonsoftware.com/articles/Unicode.html :smile:
