### ISSUE TITLE
Package list not visible on "All Packages" page

### ISSUE THREAD

**Issue by dtenenba** [Bioconductor/bioconductor.org_archive#13]
Problem:

Package list was not visible on http://www.bioconductor.org/packages/release/BiocViews.html#___Software

Steps to diagnose/fix:
- Turn on javascript console in browser
- See that variable `releaseVersion` is not defined
- This is generated by `rake write_version_info` which is part of the web site
  build process that runs every 20 minutes
- Go on staging as biocadmin and look at `~/bioc-test-web/cron.log`, see an error 
  that this rake command failed due to no free disk space.
- Free up disk space (by deleting cron.log)

There is still not much free disk space on staging. `~/bioc-test-web/bioconductor.org/workflows_tmp` uses a lot of disk space, but we can't delete it yet without changing the way workflows are built. Alternatively we may want to make the disk bigger.

**Comment by mtmorgan** [comment]
Package list is again not visible.

**Comment by b-long** [comment]
I'm taking a look at the disk usage on staging now.

**Comment by b-long** [comment]
Disk usage was at 100% again.  I've removed the `/home/biocadmin/bioc-test-web/cron.log`.  Also, I had a backup copy of spb_history's `sqlite` file (two of them, with identical MD5's), using `290M` of disk.  I've removed one and symlinked the removed location to the location that remains.   It should be noted that neither is used in production (as we're using a MySQL instance instead).  We do use SQLite in development, and [the version checked into git](https://github.com/Bioconductor/spb_history/blob/master/spb_history.sqlite) is only using `53KB`.  Of course, we likely don't want that in git long term.

The [software list](http://bioconductor.org/packages/release/BiocViews.html#___Software) is now available, `402M` is available on staging.bioconductor.org.

**Comment by jimhester** [comment]
The maEndToEnd workflow is by far the thing using the most space. Perhaps we should work with Bernd to reduce the size of the input to this workflow to be more in line with the other workflows.

``` bash
du -sh ~biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/* | sort -rh
3.6G    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/maEndToEnd
1.5G    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/CRANrepo
466M    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/proteomics
105M    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/chipseqDB
60M     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/eQTL
8.0M    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/supervised.normalization.gene.expression
5.0M    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/liftOver
1.1M    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/generegulation
716K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/rnaseqGene
672K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/annotation
284K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/ia4genet
164K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/testdocument
148K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/rnwtest
136K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/highthroughputassays
116K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/atestpackage
100K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/eQTL.bak
92K     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/sequencing
88K     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/singlevig
36K     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/rmarkdowntest
24K     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/testbiocpkg
16K     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/rmarkdown
12K     /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/arrays
4.0K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/variants
4.0K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/prune.rb
4.0K    /home/biocadmin/bioc-test-web/bioconductor.org/workflows_tmp/manifest.txt
```

**Comment by b-long** [comment]
@jimhester That's not a bad idea, `maEndToEnd` is a bit of an outlier.  I think @dtenenba and I are going to try and meet today to discuss strategies for disk usage on the machine.  You're welcome to join :smile:

**Comment by mtmorgan** [comment]
The workflows are basically meant to free us from the usual limits on size imposed by the standard build system, so I'd rather not restrict size.

**Comment by b-long** [comment]
@mtmorgan Would you prefer that we add disk space?

**Comment by mtmorgan** [comment]
Only reservation about adding more disk space is understanding the need for persistent workflows_tmp?

**Comment by b-long** [comment]
That's reasonable.  The directory name makes it seem volatile, but if it's meant to be persistent, perhaps a different name should be used.
