### ISSUE TITLE
Poor search results

### ISSUE THREAD

**Issue by b-long** [Bioconductor/bioconductor.org_archive#15]
Currently, the search results presented to a user upon some query (e.g. "DESeq2") are not very good.

**Comment by mtmorgan** [comment]
query-time update to boost release then devel landing page, then fuzzy term in title: field. SVN  c112574.

A change from pre- to post 4.0 lucene is that '/' is now a special character requiring escaping.

**Comment by b-long** [comment]
I've attempted to fixed the Ajax error handling in SVN c112865.  However, things aren't working as I'd expect according to [my test (jsfiddle)](https://jsfiddle.net/b_long/66wLyvd4/).  More confusingly, we shouldn't expect the `jQuery.ajax.error` function to be invoked according to this [popular post on StackOverflow](http://stackoverflow.com/a/19101142).  Since we are using a cross-domain request in our search (JS on `bioconductor.org` is requesting resources on `master.bioconductor.org`), it might be useful to try using a `timeout` rather than the conventional error handling, but I'll wait for feedback on this approach.

**Comment by b-long** [comment]
I'll watch this tonight, but presumably things are fixed in terms of the source code ( https://github.com/Bioconductor/bioconductor.org/commit/18a0b368f216639a72374ce0a52e34a013069b31 ).  Last remaining step is deleting the cache file, but wasn't able to get to that today.

cc/ @mtmorgan

**Comment by b-long** [comment]
The updated indexing has been committed, and although some packages ([affy](http://bioconductor.org/help/search/index.html?q=affy/)) aren't returning fantastic search results, other packages ([a4](http://bioconductor.org/help/search/index.html?q=a4/), [Rsamtools](http://bioconductor.org/help/search/index.html?q=Rsamtools/), and  [FindMyFriends](http://bioconductor.org/help/search/index.html?q=FindMyFriends/) ) are working just fine (returning release results above devel).  Considering this issue fixed.
