### ISSUE TITLE
Broken link on Package Submission page

### ISSUE THREAD

**Issue by b-long** [Bioconductor/bioconductor.org_archive#7]
There is a broken link on this page: http://www.bioconductor.org/developers/package-submission
to _"S4 classes and methods"_ , with the URL: http://www.bioconductor.org/developers/how-to/S4-classes/ .  However, that URL returns a 404 (Page Not Found) message.

cc/ @dtenenba

**Comment by dtenenba** [comment]
@b-long AFAICT there was never such a page. Might want to ask devteam about this.
`svn blame` shows that Martin authored that line.

**Comment by mtmorgan** [comment]
link removed

**Comment by dtenenba** [comment]
Not to belabor this but do we really not want to say anything about S4 objects on this page?
If not, it's fine...
@mtmorgan

**Comment by b-long** [comment]
I was referring to the page as a part of conducting package review.  @vobencha underscored that packages should "_Interoperate with other Bioconductor packages_", some additional information about S4 (etc.) might be nice.  Also, Val pointed out some common packages to me (GenomicRanges, DESeq2, and edgeR)

**Comment by mtmorgan** [comment]
The link was inadvertently introduced when I was creating a document on S4 classes and methods. Unfortunately the document remains incomplete. I've revised the page again to point to the mention of S4 classes and methods on the package guidelines page, though there's still room for improvement.
