### ISSUE TITLE
Broken link on Source Control page

### ISSUE THREAD

**Issue by b-long** [Bioconductor/bioconductor.org_archive#8]
This page : https://www.bioconductor.org/developers/source-control/ , has the following text: 

> "Maintainers can also access their packages through git and Github using the [Bioconductor Git mirrors](https://www.bioconductor.org/developers/git-mirrors/)."

However, the page : https://www.bioconductor.org/developers/git-mirrors/ does not exist.  It was probably meant to link here: https://www.bioconductor.org/developers/how-to/git-mirrors/

cc/ @vobencha

**Comment by vobencha** [comment]
Yes, I agree, thanks for catching it. Can you make this change?

**Comment by b-long** [comment]
I can, but not before the sprint end

**Comment by vobencha** [comment]
Fixed.

---

r110509 | v.obenchain | 2015-11-10 08:31:53 -0800 (Tue, 10 Nov 2015) | 2 lines

fix broken link to git mirrors

**Comment by b-long** [comment]
:+1: Nice!  Thanks, Val!
